version: 2
jobs:
  build:
    working_directory: ~/just-for-fun
    docker:
    - image: circleci/node:10.16.0
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: Install dependencies
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - ./node_modules
    - run:
        name: Check lint errors
        command: npm run lint
    - run:
        name: Unit testing
        command: npm t
